name: prepare
description: A Dart library that helps manage and configure Dart code generators.
version: 1.0.1
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/prepare

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  package_config: ^2.2.0
  pool: ^1.5.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
