name: prepare
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none # Temp
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-7.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  package_config: ^2.2.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
